[theme]
base = "light"
primaryColor = "#5145CD"
backgroundColor = "#F4F6FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#182238"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
